# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
    default: development

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.7.3
    - OpenZeppelin/openzeppelin-contracts-upgradeable@4.7.3
    - smartcontractkit/chainlink@1.11.0

# path remapping to support imports from GitHub/NPM
compiler:
    solc:
        remappings:
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.7.3/"
            - "@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.7.3/contracts/"
            - "@chainlink=smartcontractkit/chainlink@1.11.0"

reports:
    exclude_contracts:
        - SafeMath
